In [14]:
import numpy as np
from numpy import random
# python list 
n = random.randint(2,39)
m = random.randint(2,49)
num_of_rows = [[random.randint(100) for i in range(n)] for i in range(m)]
print(num_of_rows)

[[25, 77], [53, 71], [10, 89], [48, 44], [46, 6], [66, 1], [43, 68], [37, 70], [20, 48], [61, 57], [1, 53], [35, 64], [7, 62], [18, 10], [38, 37], [52, 17], [98, 68], [17, 27], [82, 18], [63, 2], [78, 5], [69, 50], [91, 31], [70, 8], [92, 83], [11, 16], [52, 16], [7, 73], [1, 78], [22, 87], [1, 58], [6, 44], [33, 69], [57, 64], [31, 5], [99, 98], [72, 13]]


In [12]:

print(num_of_rows[2])


[10, 34, 51, 20, 55, 3, 31, 4, 86, 38, 54, 9, 8, 65, 65, 26, 2, 10, 88, 29, 54]


In [10]:
x = [i[2] for i in num_of_rows]
print(x) 

[72, 67, 18, 59, 32, 46, 39, 49, 9, 52, 65, 94, 92, 95, 22, 13, 88, 63, 99, 19, 97, 96, 20, 53, 36, 75, 93, 48, 98, 51, 66, 72, 72, 86, 71, 44, 53, 17, 52, 68, 6, 65, 43, 73]


In [3]:
last_row_7 = [7 for i in num_of_rows[-1]]
num_of_rows[-1] = last_row_7
print(num_of_rows)

[[63, 88, 79, 72, 4, 50, 71, 11, 44, 43, 23, 54, 13, 84, 65, 40, 8, 40, 98, 58, 32, 12, 96, 25, 56, 66, 56, 43, 60, 76, 32, 0], [67, 90, 64, 7, 66, 79, 29, 13, 94, 21, 59, 13, 83, 40, 2, 44, 27, 15, 61, 40, 49, 16, 39, 6, 98, 10, 46, 30, 54, 95, 70, 97], [96, 5, 64, 60, 72, 77, 76, 56, 86, 78, 13, 7, 17, 64, 43, 58, 22, 38, 18, 84, 10, 60, 17, 41, 56, 31, 2, 69, 60, 92, 63, 2], [8, 17, 71, 82, 73, 79, 49, 68, 54, 86, 38, 2, 2, 38, 44, 12, 35, 41, 48, 72, 82, 67, 29, 16, 20, 18, 56, 76, 29, 13, 15, 61], [81, 99, 67, 74, 56, 89, 1, 75, 54, 82, 68, 86, 28, 19, 66, 33, 51, 17, 27, 13, 19, 15, 13, 90, 25, 23, 31, 74, 24, 47, 10, 37], [14, 43, 18, 97, 74, 82, 68, 40, 61, 86, 68, 49, 52, 64, 31, 35, 15, 96, 76, 38, 62, 44, 9, 52, 95, 54, 95, 6, 17, 64, 14, 47], [45, 7, 63, 73, 67, 18, 96, 97, 20, 39, 52, 33, 44, 93, 71, 97, 79, 30, 45, 79, 33, 26, 38, 21, 51, 89, 63, 76, 52, 52, 92, 98], [89, 95, 32, 82, 50, 78, 82, 93, 19, 68, 87, 29, 45, 96, 12, 26, 39, 1, 8, 37, 1, 72, 50, 70, 55, 99, 94, 

In [4]:
sum_one = sum(num_of_rows[0])
sum_two = sum(num_of_rows[1])
sum_one_two = sum_one + sum_two
print(sum_one_two)

3086


In [5]:

last_row = [sum_one_two for i in num_of_rows[-1]]
num_of_rows[-1] = last_row
print(num_of_rows)

[[63, 88, 79, 72, 4, 50, 71, 11, 44, 43, 23, 54, 13, 84, 65, 40, 8, 40, 98, 58, 32, 12, 96, 25, 56, 66, 56, 43, 60, 76, 32, 0], [67, 90, 64, 7, 66, 79, 29, 13, 94, 21, 59, 13, 83, 40, 2, 44, 27, 15, 61, 40, 49, 16, 39, 6, 98, 10, 46, 30, 54, 95, 70, 97], [96, 5, 64, 60, 72, 77, 76, 56, 86, 78, 13, 7, 17, 64, 43, 58, 22, 38, 18, 84, 10, 60, 17, 41, 56, 31, 2, 69, 60, 92, 63, 2], [8, 17, 71, 82, 73, 79, 49, 68, 54, 86, 38, 2, 2, 38, 44, 12, 35, 41, 48, 72, 82, 67, 29, 16, 20, 18, 56, 76, 29, 13, 15, 61], [81, 99, 67, 74, 56, 89, 1, 75, 54, 82, 68, 86, 28, 19, 66, 33, 51, 17, 27, 13, 19, 15, 13, 90, 25, 23, 31, 74, 24, 47, 10, 37], [14, 43, 18, 97, 74, 82, 68, 40, 61, 86, 68, 49, 52, 64, 31, 35, 15, 96, 76, 38, 62, 44, 9, 52, 95, 54, 95, 6, 17, 64, 14, 47], [45, 7, 63, 73, 67, 18, 96, 97, 20, 39, 52, 33, 44, 93, 71, 97, 79, 30, 45, 79, 33, 26, 38, 21, 51, 89, 63, 76, 52, 52, 92, 98], [89, 95, 32, 82, 50, 78, 82, 93, 19, 68, 87, 29, 45, 96, 12, 26, 39, 1, 8, 37, 1, 72, 50, 70, 55, 99, 94, 

In [6]:
# numpy
n = random.randint(2,39)
m = random.randint(2,49)
arr_2nd = random.randint(100, size=(n,m))
print(arr_2nd)
print(arr_2nd[2])
print(arr_2nd[:,2])


[[93 49 24 79 39  7 28 49 16 97 88]
 [92 34 48 11 97  3 89 59 86 89 47]
 [46 10 36  4 74  8 80 89 18 52 88]
 [87 82  5 26 56  4 89 48 79 53  4]
 [27 53 26 12 77 26 77 72 66 30 87]
 [50 93 63 72  0 59 27 73 67 66 41]
 [33 41 23 92 12 42 50 40 21 53 50]
 [94 88 31 59 77  0 35 23  5  4 53]
 [45 24 54 21 13 50 54 73 46 48 68]
 [35 60 99  0 69 56 45 19 48 12 39]
 [56 86 80 45 11 70 34 25 88  3 30]
 [14 20 65 52 28 75 49 99 26 90  4]
 [54 28 50 93 65 92 44 95 82 17 83]
 [89 93 20 65 60 90 46 13 79 91 50]
 [33 66 88 36 60 94 49 87 84 66  6]
 [15 63 95 43 90 93 55 46 17 21 76]
 [32 90 41 21  8 43 74 80 22 57 48]
 [89 29 51 91 80 81 71 41 88 42 93]]
[46 10 36  4 74  8 80 89 18 52 88]
[24 48 36  5 26 63 23 31 54 99 80 65 50 20 88 95 41 51]


In [7]:
last_row_7 = [7 for i in arr_2nd[-1]]
arr_2nd[-1] = last_row_7
print(arr_2nd)

[[93 49 24 79 39  7 28 49 16 97 88]
 [92 34 48 11 97  3 89 59 86 89 47]
 [46 10 36  4 74  8 80 89 18 52 88]
 [87 82  5 26 56  4 89 48 79 53  4]
 [27 53 26 12 77 26 77 72 66 30 87]
 [50 93 63 72  0 59 27 73 67 66 41]
 [33 41 23 92 12 42 50 40 21 53 50]
 [94 88 31 59 77  0 35 23  5  4 53]
 [45 24 54 21 13 50 54 73 46 48 68]
 [35 60 99  0 69 56 45 19 48 12 39]
 [56 86 80 45 11 70 34 25 88  3 30]
 [14 20 65 52 28 75 49 99 26 90  4]
 [54 28 50 93 65 92 44 95 82 17 83]
 [89 93 20 65 60 90 46 13 79 91 50]
 [33 66 88 36 60 94 49 87 84 66  6]
 [15 63 95 43 90 93 55 46 17 21 76]
 [32 90 41 21  8 43 74 80 22 57 48]
 [ 7  7  7  7  7  7  7  7  7  7  7]]


In [8]:
sum_one_two = np.sum([arr_2nd[0], arr_2nd[1]])
last_row_sum_one_two = [sum_one_two for i in arr_2nd[-1]]
arr_2nd[-1] = last_row_sum_one_two

print(arr_2nd)

[[  93   49   24   79   39    7   28   49   16   97   88]
 [  92   34   48   11   97    3   89   59   86   89   47]
 [  46   10   36    4   74    8   80   89   18   52   88]
 [  87   82    5   26   56    4   89   48   79   53    4]
 [  27   53   26   12   77   26   77   72   66   30   87]
 [  50   93   63   72    0   59   27   73   67   66   41]
 [  33   41   23   92   12   42   50   40   21   53   50]
 [  94   88   31   59   77    0   35   23    5    4   53]
 [  45   24   54   21   13   50   54   73   46   48   68]
 [  35   60   99    0   69   56   45   19   48   12   39]
 [  56   86   80   45   11   70   34   25   88    3   30]
 [  14   20   65   52   28   75   49   99   26   90    4]
 [  54   28   50   93   65   92   44   95   82   17   83]
 [  89   93   20   65   60   90   46   13   79   91   50]
 [  33   66   88   36   60   94   49   87   84   66    6]
 [  15   63   95   43   90   93   55   46   17   21   76]
 [  32   90   41   21    8   43   74   80   22   57   48]
 [1224 1224 12