In [1]:
import numpy as np 

In [2]:
a = np.array([1,2,3])

In [3]:
a

array([1, 2, 3])

In [4]:
type(a)

numpy.ndarray

In [5]:
a.shape

(3,)

In [6]:
a[0]=5

In [7]:
a

array([5, 2, 3])

2d array

In [8]:
b= np.array([[1,2,3],[4,5,6]])

In [9]:
b.shape

(2, 3)

In [10]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
b[0]

array([1, 2, 3])

In [12]:
b[1]

array([4, 5, 6])

In [13]:
b[0][0]

1

In [14]:
b[1][2]

6

In [15]:
b[:,0]

array([1, 4])

In [16]:
b[0,:]

array([1, 2, 3])

3 dimension array 


In [22]:
c= np.array([[[1,2,3],[4,5,6],[4,5,6],[4,5,6]]])

In [20]:
c

array([[[1, 2, 3],
        [4, 5, 6],
        [4, 5, 6],
        [4, 5, 6]]])